const mongoose = require('mongoose');
require('dotenv').config({ path: __dirname + '/../../.env.development' });

const Category = require('../modules/category/category.model');
const Product = require('../modules/product/product.model');
const Promotion = require('../modules/promotion/promotion.model');
const News = require('../modules/news/news.model');

const categories = [
  { name: 'Văn học Việt Nam & Thế giới', slug: 'van-hoc', description: 'Tiểu thuyết kinh điển, truyện ngắn, thơ và văn học hiện đại', image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400', order: 1 },
  { name: 'Kinh doanh & Đầu tư', slug: 'kinh-te', description: 'Tư duy tài chính, quản trị kinh doanh, khởi nghiệp và đầu tư chứng khoán', image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400', order: 2 },
  { name: 'Sách Thiếu nhi & Tranh truyện', slug: 'thieu-nhi', description: 'Tranh truyện, truyện cổ tích phát triển trí tuệ cho trẻ em', image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400', order: 3 },
  { name: 'Công nghệ thông tin & AI', slug: 'cntt', description: 'Ngôn ngữ lập trình, kiến trúc hệ thống, trí tuệ nhân tạo và thiết kế phần mềm', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400', order: 4 },
  { name: 'Học Ngoại ngữ & Từ điển', slug: 'ngoai-ngu', description: 'Giáo trình tiếng Anh, tiếng Nhật, tiếng Trung giao tiếp và luyện thi chứng chỉ', image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400', order: 5 },
];

const products = [
  // ── VĂN HỌC (van-hoc) ────────────────────────────────────────────────────────
  {
    name: 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
    slug: 'tuoi-tre-dang-gia-bao-nhieu',
    categorySlug: 'van-hoc',
    author: 'Rosie Nguyễn',
    publisher: 'NXB Nhã Nam',
    price: 80000,
    salePrice: 64000,
    stockQuantity: 150,
    soldQuantity: 389,
    viewCount: 1200,
    description: 'Cuốn sách như một lời tâm sự chân thành của một người đi trước dành cho thế hệ trẻ. Rosie chia sẻ những trải nghiệm thực tế về học tập, du lịch, định vị bản thân và khai phá tiềm năng vô hạn của bản thân trong những năm tháng thanh xuân giá trị.',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600',
    publishYear: 2023,
    pages: 280,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 345,
  },
  {
    name: 'Nhà Giả Kim (Tái Bản Mới)',
    slug: 'nha-gia-kim-tai-ban-moi',
    categorySlug: 'van-hoc',
    author: 'Paulo Coelho',
    publisher: 'NXB Hội Nhà Văn',
    price: 89000,
    salePrice: 71200,
    stockQuantity: 200,
    soldQuantity: 956,
    viewCount: 2500,
    description: 'Nhà Giả Kim là câu chuyện ngụ ngôn giàu chất thơ về hành trình của Santiago - một chàng chăn cừu Tây Ban Nha theo đuổi ước mơ tìm kiếm kho báu tại Kim Tự Tháp Ai Cập. Cuốn sách là nguồn cảm hứng bất tận giúp người đọc lắng nghe tiếng nói trái tim và theo đuổi định mệnh của mình.',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600',
    publishYear: 2024,
    pages: 208,
    isNew: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 1120,
  },
  {
    name: 'Mắt Biếc (Bìa Cứng)',
    slug: 'mat-biec-bia-cung',
    categorySlug: 'van-hoc',
    author: 'Nguyễn Nhật Ánh',
    publisher: 'NXB Trẻ',
    price: 110000,
    salePrice: 93500,
    stockQuantity: 120,
    soldQuantity: 540,
    viewCount: 1800,
    description: 'Mắt Biếc là tác phẩm tiểu thuyết lãng mạn đượm buồn của nhà văn Nguyễn Nhật Ánh. Câu chuyện xoay quanh tình bạn thanh mai trúc mã, tình yêu đơn phương âm thầm và bền bỉ của Ngạn dành cho Hà Lan - cô gái có đôi mắt biếc hút hồn.',
    coverImage: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600',
    publishYear: 2022,
    pages: 300,
    isNew: false,
    isFeatured: true,
    isBestseller: false,
    rating: 4.7,
    reviewCount: 421,
  },
  {
    name: 'Số Đỏ (Ấn Bản Kỷ Niệm)',
    slug: 'so-do-an-ban-ky-niem',
    categorySlug: 'van-hoc',
    author: 'Vũ Trọng Phụng',
    publisher: 'NXB Văn Học',
    price: 95000,
    salePrice: null,
    stockQuantity: 90,
    soldQuantity: 280,
    viewCount: 900,
    description: 'Số Đỏ là tiểu thuyết trào phúng kiệt xuất của Vũ Trọng Phụng. Tác phẩm đả kích sâu cay xã hội tư sản thành thị Hà Nội những năm đầu thế kỷ 20 thông qua hành trình đổi đời ngoạn mục của Xuân Tóc Đỏ - một kẻ hạ lưu bỗng chốc vươn lên tầng lớp thượng lưu xã hội.',
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=600',
    publishYear: 2023,
    pages: 240,
    isNew: true,
    isFeatured: false,
    isBestseller: false,
    rating: 4.6,
    reviewCount: 156,
  },
  {
    name: 'Bố Già (The Godfather)',
    slug: 'bo-gia-the-godfather',
    categorySlug: 'van-hoc',
    author: 'Mario Puzo',
    publisher: 'NXB Đông A',
    price: 145000,
    salePrice: 116000,
    stockQuantity: 80,
    soldQuantity: 412,
    viewCount: 1500,
    description: 'Bố Già là cuốn tiểu thuyết mafia kinh điển của Mario Puzo. Tác phẩm mở ra thế giới tội phạm ngầm đầy khắc nghiệt nhưng cũng tràn đầy tính nhân văn, quy tắc gia đình và những bài học ứng xử sâu sắc của ông trùm Don Vito Corleone.',
    coverImage: 'https://images.unsplash.com/photo-1618666012174-83b441c0bc76?w=600',
    publishYear: 2021,
    pages: 504,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 789,
  },

  // ── KINH TẾ (kinh-te) ────────────────────────────────────────────────────────
  {
    name: 'Đắc Nhân Tâm (Bản Chuẩn)',
    slug: 'dac-nhan-tam-ban-chuan',
    categorySlug: 'kinh-te',
    author: 'Dale Carnegie',
    publisher: 'First News Trí Việt',
    price: 86000,
    salePrice: 68800,
    stockQuantity: 300,
    soldQuantity: 1540,
    viewCount: 3200,
    description: 'Đắc Nhân Tâm là cuốn sách self-help thành công nhất mọi thời đại, hướng dẫn nghệ thuật giao tiếp thu phục lòng người, tạo dựng thiện cảm và thuyết phục người khác hiệu quả nhất, giúp ích to lớn cho sự nghiệp kinh doanh và quản trị.',
    coverImage: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600',
    publishYear: 2023,
    pages: 320,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 2310,
  },
  {
    name: 'Cha Giàu Cha Nghèo (Tập 1)',
    slug: 'cha-giau-cha-ngheo-tap-1',
    categorySlug: 'kinh-te',
    author: 'Robert T. Kiyosaki',
    publisher: 'NXB Trẻ',
    price: 99000,
    salePrice: 84150,
    stockQuantity: 250,
    soldQuantity: 1080,
    viewCount: 2800,
    description: 'Cuốn sách vỡ lòng về tư duy tài chính xuất sắc nhất. Robert Kiyosaki chia sẻ những bài học tiền bạc quý giá từ hai người cha, giải thích vì sao người giàu ngày càng giàu lên còn người nghèo mãi luẩn quẩn trong vòng nợ nần.',
    coverImage: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=600',
    publishYear: 2024,
    pages: 360,
    isNew: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 940,
  },
  {
    name: 'Bí Mật Tư Duy Triệu Phú',
    slug: 'bi-mat-tu-duy-trieu-phu',
    categorySlug: 'kinh-te',
    author: 'T. Harv Eker',
    publisher: 'NXB Tổng hợp TP.HCM',
    price: 115000,
    salePrice: 92000,
    stockQuantity: 180,
    soldQuantity: 620,
    viewCount: 1400,
    description: 'T. Harv Eker tiết lộ những kế hoạch tài chính đã được thiết lập sẵn trong tâm thức của mỗi người. Cuốn sách giúp bạn định hình lại tư duy tiền bạc, loại bỏ những rào cản vô hình để mở lối cho sự giàu có vượt bậc.',
    coverImage: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=600',
    publishYear: 2023,
    pages: 288,
    isNew: false,
    isFeatured: false,
    isBestseller: true,
    rating: 4.7,
    reviewCount: 480,
  },
  {
    name: 'Tư Duy Nhanh Và Chậm',
    slug: 'tu-duy-nhanh-va-cham',
    categorySlug: 'kinh-te',
    author: 'Daniel Kahneman',
    publisher: 'NXB Thế Giới',
    price: 220000,
    salePrice: 176000,
    stockQuantity: 110,
    soldQuantity: 340,
    viewCount: 1100,
    description: 'Tác phẩm nổi tiếng giải mã cơ chế tư duy của con người dưới góc nhìn tâm lý học hành vi của nhà khoa học đoạt giải Nobel Daniel Kahneman. Một cuốn sách buộc bạn phải nhìn nhận lại các quyết định mua sắm, đầu tư hàng ngày.',
    coverImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600',
    publishYear: 2022,
    pages: 512,
    isNew: false,
    isFeatured: true,
    isBestseller: false,
    rating: 4.6,
    reviewCount: 220,
  },
  {
    name: 'Phương Thức Toyota (The Toyota Way)',
    slug: 'phuong-thuc-toyota-the-toyota-way',
    categorySlug: 'kinh-te',
    author: 'Jeffrey K. Liker',
    publisher: 'NXB Tổng Hợp',
    price: 195000,
    salePrice: null,
    stockQuantity: 60,
    soldQuantity: 112,
    viewCount: 450,
    description: 'Cuốn sách gối đầu giường về tối ưu hóa quy trình sản xuất và quản trị nhân sự theo triết lý tinh gọn (Lean) của hãng Toyota nổi tiếng toàn cầu.',
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600',
    publishYear: 2021,
    pages: 440,
    isNew: false,
    isFeatured: false,
    isBestseller: false,
    rating: 4.5,
    reviewCount: 96,
  },

  // ── THIẾU NHI (thieu-nhi) ───────────────────────────────────────────────────
  {
    name: 'Doraemon Truyện Ngắn - Tập 1',
    slug: 'doraemon-truyen-ngan-tap-1',
    categorySlug: 'thieu-nhi',
    author: 'Fujiko F. Fujio',
    publisher: 'NXB Kim Đồng',
    price: 25000,
    salePrice: null,
    stockQuantity: 500,
    soldQuantity: 2450,
    viewCount: 4200,
    description: 'Chú mèo máy Doraemon thông minh từ tương lai quay về quá khứ để giúp đỡ cậu bé Nobita hậu đậu thông qua những bảo bối thần kỳ vô cùng lý thú và đầy tính nhân văn.',
    coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600',
    publishYear: 2024,
    pages: 192,
    isNew: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 1920,
  },
  {
    name: 'Thám Tử Lừng Danh Conan - Tập 100',
    slug: 'tham-tu-lung-danh-conan-tap-100',
    categorySlug: 'thieu-nhi',
    author: 'Gosho Aoyama',
    publisher: 'NXB Kim Đồng',
    price: 30000,
    salePrice: 25500,
    stockQuantity: 400,
    soldQuantity: 1890,
    viewCount: 3800,
    description: 'Cột mốc tập 100 huyền thoại của bộ truyện trinh thám nổi tiếng nhất hành tinh. Những màn đấu trí nảy lửa giữa cậu bé Conan và Tổ chức Áo Đen bí ẩn.',
    coverImage: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600',
    publishYear: 2023,
    pages: 180,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 1140,
  },
  {
    name: 'Cổ Tích Việt Nam Chọn Lọc (Bản Đẹp)',
    slug: 'co-tich-viet-nam-chon-loc-ban-dep',
    categorySlug: 'thieu-nhi',
    author: 'Nguyễn Đổng Chi',
    publisher: 'NXB Giáo Dục',
    price: 65000,
    salePrice: 52000,
    stockQuantity: 150,
    soldQuantity: 310,
    viewCount: 750,
    description: 'Tuyển chọn những câu truyện cổ tích thấm đượm lòng nhân ái, lòng yêu nước và đạo lý làm người của dân tộc Việt Nam như Tấm Cám, Thánh Gióng, Thạch Sanh.',
    coverImage: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=600',
    publishYear: 2022,
    pages: 140,
    isNew: false,
    isFeatured: false,
    isBestseller: false,
    rating: 4.6,
    reviewCount: 98,
  },
  {
    name: 'Kính Vạn Hoa (Trọn Bộ 9 Tập - Tập 1)',
    slug: 'kinh-van-hoa-tap-1',
    categorySlug: 'thieu-nhi',
    author: 'Nguyễn Nhật Ánh',
    publisher: 'NXB Kim Đồng',
    price: 85000,
    salePrice: 72250,
    stockQuantity: 160,
    soldQuantity: 420,
    viewCount: 1250,
    description: 'Kính Vạn Hoa mở ra những cuộc phiêu lưu lý thú, tràn ngập tiếng cười tinh nghịch của bộ ba Quý ròm, Tiểu Long và Hạnh cận thời học sinh.',
    coverImage: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600',
    publishYear: 2023,
    pages: 280,
    isNew: true,
    isFeatured: false,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 310,
  },

  // ── CNTT (cntt) ─────────────────────────────────────────────────────────────
  {
    name: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    slug: 'clean-code-original',
    categorySlug: 'cntt',
    author: 'Robert C. Martin (Uncle Bob)',
    publisher: 'Prentice Hall',
    price: 320000,
    salePrice: 256000,
    stockQuantity: 120,
    soldQuantity: 410,
    viewCount: 1650,
    description: 'Cuốn sách gối đầu giường của mọi nhà phát triển phần mềm muốn nâng tầm kỹ năng. Uncle Bob chỉ rõ các nguyên tắc, phương pháp viết mã nguồn sạch, dễ bảo trì, tối ưu hiệu năng và tránh rủi ro kỹ thuật.',
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600',
    publishYear: 2022,
    pages: 464,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 560,
  },
  {
    name: 'Clean Architecture (Bản Dịch Tiếng Việt)',
    slug: 'clean-architecture-vietnamese',
    categorySlug: 'cntt',
    author: 'Robert C. Martin',
    publisher: 'NXB Khoa Học Kỹ Thuật',
    price: 240000,
    salePrice: 204000,
    stockQuantity: 80,
    soldQuantity: 180,
    viewCount: 850,
    description: 'Kiến Trúc Sạch là kim chỉ nam giúp các kỹ sư xây dựng hệ thống phần mềm có tính mở rộng cao, độc lập với các thư viện bên ngoài và dễ dàng thử nghiệm tự động.',
    coverImage: 'https://images.unsplash.com/photo-1605379399642-870262d3d051?w=600',
    publishYear: 2023,
    pages: 420,
    isNew: true,
    isFeatured: true,
    isBestseller: false,
    rating: 4.8,
    reviewCount: 140,
  },
  {
    name: 'JavaScript: The Definitive Guide (7th Edition)',
    slug: 'javascript-the-definitive-guide-7th',
    categorySlug: 'cntt',
    author: 'David Flanagan',
    publisher: "O'Reilly Media",
    price: 450000,
    salePrice: null,
    stockQuantity: 50,
    soldQuantity: 96,
    viewCount: 650,
    description: 'Cuốn "Kinh thánh" hoàn hảo nhất về ngôn ngữ JavaScript, bao gồm tất cả các khía cạnh từ cơ bản, ES6+, xử lý bất đồng bộ, lập trình phía máy chủ với Node.js.',
    coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600',
    publishYear: 2021,
    pages: 706,
    isNew: false,
    isFeatured: false,
    isBestseller: true,
    rating: 4.7,
    reviewCount: 88,
  },
  {
    name: 'Thiết Kế Hệ Thống Phân Tán (System Design)',
    slug: 'thiet-ke-he-thong-phan-tan-system-design',
    categorySlug: 'cntt',
    author: 'Alex Xu',
    publisher: 'NXB Thông Tin Truyền Thông',
    price: 280000,
    salePrice: 224000,
    stockQuantity: 90,
    soldQuantity: 320,
    viewCount: 1950,
    description: 'Cẩm nang tuyệt vời giúp lập trình viên chuẩn bị cho các buổi phỏng vấn thiết kế hệ thống lớn tầm cỡ ByteDance, Google, Facebook. Hướng dẫn thiết kế Rate Limiter, Chat, Youtube.',
    coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600',
    publishYear: 2023,
    pages: 350,
    isNew: true,
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 410,
  },
  {
    name: 'Deep Learning (Lập Trình Trí Tuệ Nhân Tạo)',
    slug: 'deep-learning-lan-goodfellow',
    categorySlug: 'cntt',
    author: 'Ian Goodfellow',
    publisher: 'MIT Press',
    price: 520000,
    salePrice: 468000,
    stockQuantity: 40,
    soldQuantity: 74,
    viewCount: 520,
    description: 'Cuốn giáo trình lý thuyết AI toàn diện hàng đầu thế giới được khuyên đọc bởi Elon Musk. Cung cấp nền tảng toán học, mạng nơ-ron tích chập (CNN), mạng hồi quy (RNN).',
    coverImage: 'https://images.unsplash.com/photo-1527474305487-b87b222841cc?w=600',
    publishYear: 2022,
    pages: 800,
    isNew: false,
    isFeatured: false,
    isBestseller: false,
    rating: 4.6,
    reviewCount: 52,
  },

  // ── NGOẠI NGỮ (ngoai-ngu) ───────────────────────────────────────────────────
  {
    name: 'English Grammar in Use (5th Edition)',
    slug: 'english-grammar-in-use-5th-edition',
    categorySlug: 'ngoai-ngu',
    author: 'Raymond Murphy',
    publisher: 'Cambridge University Press',
    price: 220000,
    salePrice: 176000,
    stockQuantity: 350,
    soldQuantity: 1890,
    viewCount: 3100,
    description: 'Cuốn sách ngữ pháp bán chạy nhất thế giới dành cho người học tiếng Anh trung cấp. Trình bày dạng 2 trang đối xứng cực kỳ thông minh: một bên lý thuyết, một bên bài tập thực hành.',
    coverImage: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=600',
    publishYear: 2023,
    pages: 390,
    isNew: false,
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 2200,
  },
  {
    name: 'Giáo trình Minna no Nihongo I - Sơ Cấp',
    slug: 'giao-trinh-minna-no-nihongo-1',
    categorySlug: 'ngoai-ngu',
    author: '3A Corporation',
    publisher: 'NXB Trẻ',
    price: 130000,
    salePrice: null,
    stockQuantity: 150,
    soldQuantity: 670,
    viewCount: 1200,
    description: 'Cuốn sách giáo trình học tiếng Nhật giao tiếp nhập môn chuẩn xác nhất dành cho các bạn có mục tiêu du học hoặc thi chứng chỉ JLPT N5, N4.',
    coverImage: 'https://images.unsplash.com/photo-1528164344705-47542687000d?w=600',
    publishYear: 2022,
    pages: 280,
    isNew: false,
    isFeatured: false,
    isBestseller: true,
    rating: 4.8,
    reviewCount: 512,
  },
  {
    name: 'Luyện Siêu Trí Nhớ Từ Vựng Tiếng Anh',
    slug: 'luyen-sieu-tri-nho-tu-vung-tieng-anh',
    categorySlug: 'ngoai-ngu',
    author: 'Nguyễn Anh Đức',
    publisher: 'NXB Hồng Đức',
    price: 180000,
    salePrice: 144000,
    stockQuantity: 140,
    soldQuantity: 410,
    viewCount: 950,
    description: 'Ứng dụng phương pháp học Do Thái thông minh giúp ghi nhớ nhanh chóng hơn 1500 từ vựng cốt lõi thường xuất hiện trong đề thi TOEIC, IELTS.',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600',
    publishYear: 2023,
    pages: 340,
    isNew: true,
    isFeatured: true,
    isBestseller: false,
    rating: 4.5,
    reviewCount: 198,
  },
];

const promotions = [
  {
    title: 'Đại Tiệc Mùa Hè - Ưu đãi đến 50%',
    slug: 'dai-tiec-mua-he-uu-dai-50',
    description: 'Đại tiệc sách hè tưng bừng! Giảm giá cực sâu lên tới 50% cho các tác phẩm Văn học kiệt xuất và truyện tranh thiếu nhi lý thú.',
    discountPercent: 50,
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200',
    startDate: new Date('2026-06-01'),
    endDate: new Date('2026-08-31'),
    link: '/products',
  },
  {
    title: 'Khám Phá Tri Thức - Lập trình giảm 20%',
    slug: 'kham-pha-tri-thuc-lap-trinh-giam-20',
    description: 'Ưu đãi đặc biệt giảm ngay 20% cho tất cả các sách chuyên ngành CNTT, Trí tuệ nhân tạo và Thiết kế hệ thống System Design hàng đầu.',
    discountPercent: 20,
    image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=1200',
    startDate: new Date('2026-05-01'),
    endDate: new Date('2026-06-30'),
    link: '/products?category=cntt',
  },
  {
    title: 'Flash Sale Ngày Vàng - Giảm 30%',
    slug: 'flash-sale-ngay-vang-giam-30',
    description: 'Ngày hội mua sắm vàng! Giảm ngay 30% tổng hóa đơn cho 200 khách hàng nhanh tay mua sắm trong khung giờ vàng ngày hôm nay.',
    discountPercent: 30,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=1200',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    link: '/products',
  },
];

const news = [
  {
    title: 'Mùa Hè 2026 Đọc Gì? Top 10 Cuốn Sách Nâng Tầm Bản Thân Nhất',
    slug: 'mua-he-2026-doc-gi-top-10',
    content: `<p>Mùa hè là dịp tuyệt vời để thư giãn và nạp năng lượng tri thức. Dưới đây là top sách bán chạy hàng đầu giúp bạn nâng tầm tư duy:</p>
    <h3>1. Nhà Giả Kim (Paulo Coelho)</h3>
    <p>Hành trình tìm kiếm ước mơ đầy triết lý nhân văn sâu sắc.</p>
    <h3>2. Đắc Nhân Tâm (Dale Carnegie)</h3>
    <p>Thuật đối xử và tạo dựng thiện cảm tối quan trọng trong kinh doanh và đời sống.</p>`,
    excerpt: 'Cùng điểm qua danh sách 10 cuốn sách kiệt tác được độc giả đón đọc nhiều nhất đầu năm 2026.',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    author: 'Hội Đồng Học Thuật BookStore',
    category: 'Cảm hứng đọc',
    tags: ['sách hay', 'mùa hè 2026', 'review sách'],
    isFeatured: true,
    viewCount: 2450,
  },
  {
    title: 'Xu Hướng AI & Machine Learning Bùng Nổ Trong Năm 2026',
    slug: 'xu-huong-ai-machine-learning-2026',
    content: `<p>Sự trỗi dậy của các mô hình ngôn ngữ lớn LLM đòi hỏi lập trình viên phải liên tục cập nhật kiến thức. Cuốn giáo trình Deep Learning của Ian Goodfellow tiếp tục là kim chỉ nam hàng đầu cho giới nghiên cứu công nghệ tại Việt Nam.</p>`,
    excerpt: 'Lập trình viên cần chuẩn bị gì trước làn sóng công nghệ trí tuệ nhân tạo thế hệ mới?',
    image: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800',
    author: 'Kỹ Sư Công Nghệ BookStore',
    category: 'Xu hướng công nghệ',
    tags: ['AI', 'Python', 'System Design'],
    isFeatured: true,
    viewCount: 1890,
  },
  {
    title: 'Kỷ Niệm Cột Mốc 100 Tập Thám Tử Lừng Danh Conan Tại Việt Nam',
    slug: 'ky-niem-col-moc-100-tap-conan',
    content: `<p>NXB Kim Đồng chính thức phát hành ấn bản đặc biệt kỷ niệm tập thứ 100 của bộ truyện Conan. Đây là cơ hội tuyệt vời cho các fan hâm mộ trinh thám sở hữu những trang sách màu kỷ niệm sắc nét và vô cùng giá trị.</p>`,
    excerpt: 'NXB Kim Đồng phát hành tập 100 Conan kèm quà tặng bưu ảnh cực kỳ hot.',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800',
    author: 'Tin tức Măng Non',
    category: 'Manga & Comic',
    tags: ['Conan tập 100', 'truyện thiếu nhi', 'Kim Đồng'],
    isFeatured: false,
    viewCount: 950,
  },
];

async function seed() {
  try {
    console.log('🔄 Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    console.log('🗑️  Clearing existing data...');
    await Promise.all([
      Category.deleteMany({}),
      Product.deleteMany({}),
      Promotion.deleteMany({}),
      News.deleteMany({}),
    ]);

    // Create categories and get their IDs
    console.log('📚 Creating categories...');
    const createdCategories = await Category.insertMany(categories);
    const categoryMap = {};
    createdCategories.forEach((cat) => {
      categoryMap[cat.slug] = cat._id;
    });
    console.log(`✅ Created ${createdCategories.length} categories`);

    // Create products with correctly matched category IDs
    console.log('📖 Creating products...');
    const productsWithCategories = products.map((p) => {
      const catId = categoryMap[p.categorySlug];
      if (!catId) {
        console.warn(`⚠️ Warning: Category slug '${p.categorySlug}' not found for product '${p.name}'! Defaulting to 'van-hoc'.`);
      }
      return {
        ...p,
        category: catId || categoryMap['van-hoc'],
      };
    });

    const createdProducts = await Product.insertMany(productsWithCategories);
    console.log(`✅ Created ${createdProducts.length} products`);

    // Create promotions
    console.log('🎉 Creating promotions...');
    const createdPromotions = await Promotion.insertMany(promotions);
    console.log(`✅ Created ${createdPromotions.length} promotions`);

    // Create news
    console.log('📰 Creating news...');
    const createdNews = await News.insertMany(news);
    console.log(`✅ Created ${createdNews.length} news articles`);

    console.log('\n🎊 Seed completed successfully!');
    console.log(`
Summary:
- Categories: ${createdCategories.length}
- Products: ${createdProducts.length} (Tất cả được ánh xạ danh mục chính xác 100% và gán viewCount > 0!)
- Promotions: ${createdPromotions.length}
- News: ${createdNews.length}
    `);

    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
}

seed();
